# golangci-lint configuration for security and code quality
run:
  timeout: 5m
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*_test\\.go$"

linters:
  enable:
    # Security
    - gosec
    - gocritic
    
    # Code quality
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - staticcheck
    - gosimple
    - stylecheck
    - unused
    - typecheck
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - varcheck
    - deadcode
    
    # Performance
    - prealloc
    
    # Best practices
    - errcheck
    - goconst
    - gocyclo
    - dupl
    - gocognit
    - funlen
    - nestif
    
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - wsl

linters-settings:
  gosec:
    excludes:
      - G104  # Audit errors not checked
      - G304  # File path provided as taint input
    config:
      global:
        audit: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  funlen:
    lines: 100
    statements: 50
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gocognit:
    min-complexity: 20
  
  nestif:
    min-complexity: 4
  
  goimports:
    local-prefixes: github.com/analyst/pcf-mcp

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
    
    # Exclude known patterns
    - linters:
        - stylecheck
      text: "ST1000:"
    
    # Exclude error checks in main
    - path: cmd/pcf-mcp/main.go
      linters:
        - errcheck
      text: "Error return value of"
  
  # Maximum issues count per one linter.
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text.
  max-same-issues: 3
  
  # Show only new issues
  new: false

severity:
  default-severity: warning