# Production environment values
replicaCount: 5

image:
  pullPolicy: IfNotPresent
  tag: "0.9.0"

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: pcf-mcp.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: pcf-mcp-tls
      hosts:
        - pcf-mcp.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

config:
  server:
    maxConcurrentTools: 50
    authRequired: true
    # authToken should be set via --set or external secret
    
  pcf:
    url: https://pcf.example.com
    # apiKey should be set via --set or external secret
    
  logging:
    level: info
    format: json
    
  tracing:
    enabled: true
    endpoint: http://jaeger-collector:14268/api/traces
    samplingRate: 0.01

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - pcf-mcp
      topologyKey: kubernetes.io/hostname