apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-mcp-config
  namespace: pcf-mcp
  labels:
    app.kubernetes.io/name: pcf-mcp
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: pcf-mcp
data:
  config.yaml: |
    server:
      transport: http
      host: 0.0.0.0
      port: 8080
      max_concurrent_tools: 20
      tool_timeout: 60s
      read_timeout: 30s
      write_timeout: 30s
      
    pcf:
      timeout: 30s
      max_retries: 3
      insecure_skip_verify: false
      
    logging:
      level: info
      format: json
      add_source: false
      
    metrics:
      enabled: true
      port: 9090
      path: /metrics
      
    tracing:
      enabled: false
      exporter: otlp
      sampling_rate: 0.1
      service_name: pcf-mcp