apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pcf-mcp

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- poddisruptionbudget.yaml
- networkpolicy.yaml

commonLabels:
  app: pcf-mcp
  version: "0.9.0"

images:
- name: pcf-mcp
  newTag: latest