apiVersion: v1
kind: Secret
metadata:
  name: pcf-mcp-secrets
  namespace: pcf-mcp
  labels:
    app.kubernetes.io/name: pcf-mcp
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: pcf-mcp
type: Opaque
stringData:
  # IMPORTANT: Replace these with your actual values
  # Consider using sealed-secrets or external-secrets in production
  pcf-api-key: "your-pcf-api-key-here"
  auth-token: "your-bearer-token-here"