apiVersion: v1
kind: ServiceAccount
metadata:
  name: pcf-mcp
  namespace: pcf-mcp
  labels:
    app.kubernetes.io/name: pcf-mcp
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: pcf-mcp
automountServiceAccountToken: false