# Example using External Secrets Operator with AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: pcf-mcp
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: pcf-mcp-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pcf-mcp-secrets
  namespace: pcf-mcp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pcf-mcp-secrets
    creationPolicy: Owner
  data:
  - secretKey: pcf-api-key
    remoteRef:
      key: /pcf-mcp/production/api-key
  - secretKey: auth-token
    remoteRef:
      key: /pcf-mcp/production/auth-token
---
# Example using Sealed Secrets
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pcf-mcp-secrets
  namespace: pcf-mcp
spec:
  encryptedData:
    pcf-api-key: AgA... # Encrypted value
    auth-token: AgB...  # Encrypted value
  template:
    metadata:
      name: pcf-mcp-secrets
      namespace: pcf-mcp
    type: Opaque