apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pcf-mcp-prod

bases:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
- name: pcf-mcp
  count: 5

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- hpa.yaml

resources:
- ingress.yaml

configMapGenerator:
- name: pcf-mcp-config
  behavior: merge
  literals:
  - pcf-url=https://pcf.example.com