apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pcf-mcp-dev

bases:
- ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

configMapGenerator:
- name: pcf-mcp-config
  behavior: merge
  literals:
  - pcf-url=http://pcf-dev.example.com

secretGenerator:
- name: pcf-mcp-secrets
  behavior: replace
  literals:
  - pcf-api-key=dev-api-key
  - auth-token=dev-token