{{- if not .Values.externalSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pcf-mcp.fullname" . }}
  labels:
    {{- include "pcf-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.pcf.apiKey }}
  pcf-api-key: {{ .Values.config.pcf.apiKey | quote }}
  {{- else }}
  pcf-api-key: "placeholder-api-key"
  {{- end }}
  {{- if .Values.config.server.authToken }}
  auth-token: {{ .Values.config.server.authToken | quote }}
  {{- else }}
  auth-token: "placeholder-auth-token"
  {{- end }}
{{- end }}